trace:
  endpoint: http://127.0.0.1:14268/api/traces
server:
  http:
    addr: 0.0.0.0:8007
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9007
    timeout: 1s
data:
  kafka:
    addrs:
      - 127.0.0.1:9092