// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: v1/catalog.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNum       int64                  `protobuf:"varint,1,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductReq) Reset() {
	*x = ListProductReq{}
	mi := &file_v1_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductReq) ProtoMessage() {}

func (x *ListProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductReq.ProtoReflect.Descriptor instead.
func (*ListProductReq) Descriptor() ([]byte, []int) {
	return file_v1_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *ListProductReq) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *ListProductReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListProductNextTokenReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum number of books to return. The service may return fewer than
	// this value.
	// If unspecified, at most 50 books will be returned.
	// The maximum value is 1000; values above 1000 will be coerced to 1000.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// A page token, received from a previous `ListBooks` call.
	// Provide this to retrieve the subsequent page.
	//
	// When paginating, all other parameters provided to `ListBooks` must match
	// the call that provided the page token.
	PageToken     string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductNextTokenReq) Reset() {
	*x = ListProductNextTokenReq{}
	mi := &file_v1_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductNextTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductNextTokenReq) ProtoMessage() {}

func (x *ListProductNextTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductNextTokenReq.ProtoReflect.Descriptor instead.
func (*ListProductNextTokenReq) Descriptor() ([]byte, []int) {
	return file_v1_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *ListProductNextTokenReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListProductNextTokenReq) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListProductReply struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Results       []*ListProductReply_Product `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductReply) Reset() {
	*x = ListProductReply{}
	mi := &file_v1_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductReply) ProtoMessage() {}

func (x *ListProductReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductReply.ProtoReflect.Descriptor instead.
func (*ListProductReply) Descriptor() ([]byte, []int) {
	return file_v1_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *ListProductReply) GetResults() []*ListProductReply_Product {
	if x != nil {
		return x.Results
	}
	return nil
}

type ListProductReplyNextToken struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Results       []*ListProductReplyNextToken_Product `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	NextPageToken string                               `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductReplyNextToken) Reset() {
	*x = ListProductReplyNextToken{}
	mi := &file_v1_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductReplyNextToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductReplyNextToken) ProtoMessage() {}

func (x *ListProductReplyNextToken) ProtoReflect() protoreflect.Message {
	mi := &file_v1_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductReplyNextToken.ProtoReflect.Descriptor instead.
func (*ListProductReplyNextToken) Descriptor() ([]byte, []int) {
	return file_v1_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *ListProductReplyNextToken) GetResults() []*ListProductReplyNextToken_Product {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ListProductReplyNextToken) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CreateProductReq struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Name          string                    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                    `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Count         int64                     `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Image         []*CreateProductReq_Image `protobuf:"bytes,4,rep,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductReq) Reset() {
	*x = CreateProductReq{}
	mi := &file_v1_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductReq) ProtoMessage() {}

func (x *CreateProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductReq.ProtoReflect.Descriptor instead.
func (*CreateProductReq) Descriptor() ([]byte, []int) {
	return file_v1_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *CreateProductReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductReq) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *CreateProductReq) GetImage() []*CreateProductReq_Image {
	if x != nil {
		return x.Image
	}
	return nil
}

type CreateProductReply struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Id            int64                       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                      `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Count         int64                       `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Image         []*CreateProductReply_Image `protobuf:"bytes,5,rep,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductReply) Reset() {
	*x = CreateProductReply{}
	mi := &file_v1_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductReply) ProtoMessage() {}

func (x *CreateProductReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductReply.ProtoReflect.Descriptor instead.
func (*CreateProductReply) Descriptor() ([]byte, []int) {
	return file_v1_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *CreateProductReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateProductReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductReply) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductReply) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *CreateProductReply) GetImage() []*CreateProductReply_Image {
	if x != nil {
		return x.Image
	}
	return nil
}

type GetProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductReq) Reset() {
	*x = GetProductReq{}
	mi := &file_v1_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductReq) ProtoMessage() {}

func (x *GetProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductReq.ProtoReflect.Descriptor instead.
func (*GetProductReq) Descriptor() ([]byte, []int) {
	return file_v1_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *GetProductReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetProductReply struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Id            int64                    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Count         int64                    `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Image         []*GetProductReply_Image `protobuf:"bytes,5,rep,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductReply) Reset() {
	*x = GetProductReply{}
	mi := &file_v1_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductReply) ProtoMessage() {}

func (x *GetProductReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductReply.ProtoReflect.Descriptor instead.
func (*GetProductReply) Descriptor() ([]byte, []int) {
	return file_v1_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *GetProductReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetProductReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetProductReply) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetProductReply) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetProductReply) GetImage() []*GetProductReply_Image {
	if x != nil {
		return x.Image
	}
	return nil
}

type UpdateProductReq struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Id            int64                     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                    `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Count         int64                     `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Image         []*UpdateProductReq_Image `protobuf:"bytes,5,rep,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductReq) Reset() {
	*x = UpdateProductReq{}
	mi := &file_v1_catalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductReq) ProtoMessage() {}

func (x *UpdateProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_catalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductReq.ProtoReflect.Descriptor instead.
func (*UpdateProductReq) Descriptor() ([]byte, []int) {
	return file_v1_catalog_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateProductReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProductReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProductReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProductReq) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *UpdateProductReq) GetImage() []*UpdateProductReq_Image {
	if x != nil {
		return x.Image
	}
	return nil
}

type UpdateProductReply struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Id            int64                       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                      `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Count         int64                       `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Image         []*UpdateProductReply_Image `protobuf:"bytes,5,rep,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductReply) Reset() {
	*x = UpdateProductReply{}
	mi := &file_v1_catalog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductReply) ProtoMessage() {}

func (x *UpdateProductReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_catalog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductReply.ProtoReflect.Descriptor instead.
func (*UpdateProductReply) Descriptor() ([]byte, []int) {
	return file_v1_catalog_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateProductReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProductReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProductReply) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProductReply) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *UpdateProductReply) GetImage() []*UpdateProductReply_Image {
	if x != nil {
		return x.Image
	}
	return nil
}

type DeleteProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductReq) Reset() {
	*x = DeleteProductReq{}
	mi := &file_v1_catalog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductReq) ProtoMessage() {}

func (x *DeleteProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_catalog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductReq.ProtoReflect.Descriptor instead.
func (*DeleteProductReq) Descriptor() ([]byte, []int) {
	return file_v1_catalog_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteProductReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteProductReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductReply) Reset() {
	*x = DeleteProductReply{}
	mi := &file_v1_catalog_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductReply) ProtoMessage() {}

func (x *DeleteProductReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_catalog_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductReply.ProtoReflect.Descriptor instead.
func (*DeleteProductReply) Descriptor() ([]byte, []int) {
	return file_v1_catalog_proto_rawDescGZIP(), []int{11}
}

type ListProductReply_Product struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Id            int64                             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                            `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Count         int64                             `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Image         []*ListProductReply_Product_Image `protobuf:"bytes,5,rep,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductReply_Product) Reset() {
	*x = ListProductReply_Product{}
	mi := &file_v1_catalog_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductReply_Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductReply_Product) ProtoMessage() {}

func (x *ListProductReply_Product) ProtoReflect() protoreflect.Message {
	mi := &file_v1_catalog_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductReply_Product.ProtoReflect.Descriptor instead.
func (*ListProductReply_Product) Descriptor() ([]byte, []int) {
	return file_v1_catalog_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ListProductReply_Product) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListProductReply_Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListProductReply_Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ListProductReply_Product) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ListProductReply_Product) GetImage() []*ListProductReply_Product_Image {
	if x != nil {
		return x.Image
	}
	return nil
}

type ListProductReply_Product_Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductReply_Product_Image) Reset() {
	*x = ListProductReply_Product_Image{}
	mi := &file_v1_catalog_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductReply_Product_Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductReply_Product_Image) ProtoMessage() {}

func (x *ListProductReply_Product_Image) ProtoReflect() protoreflect.Message {
	mi := &file_v1_catalog_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductReply_Product_Image.ProtoReflect.Descriptor instead.
func (*ListProductReply_Product_Image) Descriptor() ([]byte, []int) {
	return file_v1_catalog_proto_rawDescGZIP(), []int{2, 0, 0}
}

func (x *ListProductReply_Product_Image) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ListProductReplyNextToken_Product struct {
	state         protoimpl.MessageState                     `protogen:"open.v1"`
	Id            int64                                      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                                     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                                     `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Count         int64                                      `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Image         []*ListProductReplyNextToken_Product_Image `protobuf:"bytes,5,rep,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductReplyNextToken_Product) Reset() {
	*x = ListProductReplyNextToken_Product{}
	mi := &file_v1_catalog_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductReplyNextToken_Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductReplyNextToken_Product) ProtoMessage() {}

func (x *ListProductReplyNextToken_Product) ProtoReflect() protoreflect.Message {
	mi := &file_v1_catalog_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductReplyNextToken_Product.ProtoReflect.Descriptor instead.
func (*ListProductReplyNextToken_Product) Descriptor() ([]byte, []int) {
	return file_v1_catalog_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ListProductReplyNextToken_Product) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListProductReplyNextToken_Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListProductReplyNextToken_Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ListProductReplyNextToken_Product) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ListProductReplyNextToken_Product) GetImage() []*ListProductReplyNextToken_Product_Image {
	if x != nil {
		return x.Image
	}
	return nil
}

type ListProductReplyNextToken_Product_Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductReplyNextToken_Product_Image) Reset() {
	*x = ListProductReplyNextToken_Product_Image{}
	mi := &file_v1_catalog_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductReplyNextToken_Product_Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductReplyNextToken_Product_Image) ProtoMessage() {}

func (x *ListProductReplyNextToken_Product_Image) ProtoReflect() protoreflect.Message {
	mi := &file_v1_catalog_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductReplyNextToken_Product_Image.ProtoReflect.Descriptor instead.
func (*ListProductReplyNextToken_Product_Image) Descriptor() ([]byte, []int) {
	return file_v1_catalog_proto_rawDescGZIP(), []int{3, 0, 0}
}

func (x *ListProductReplyNextToken_Product_Image) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CreateProductReq_Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductReq_Image) Reset() {
	*x = CreateProductReq_Image{}
	mi := &file_v1_catalog_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductReq_Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductReq_Image) ProtoMessage() {}

func (x *CreateProductReq_Image) ProtoReflect() protoreflect.Message {
	mi := &file_v1_catalog_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductReq_Image.ProtoReflect.Descriptor instead.
func (*CreateProductReq_Image) Descriptor() ([]byte, []int) {
	return file_v1_catalog_proto_rawDescGZIP(), []int{4, 0}
}

func (x *CreateProductReq_Image) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CreateProductReply_Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductReply_Image) Reset() {
	*x = CreateProductReply_Image{}
	mi := &file_v1_catalog_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductReply_Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductReply_Image) ProtoMessage() {}

func (x *CreateProductReply_Image) ProtoReflect() protoreflect.Message {
	mi := &file_v1_catalog_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductReply_Image.ProtoReflect.Descriptor instead.
func (*CreateProductReply_Image) Descriptor() ([]byte, []int) {
	return file_v1_catalog_proto_rawDescGZIP(), []int{5, 0}
}

func (x *CreateProductReply_Image) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetProductReply_Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductReply_Image) Reset() {
	*x = GetProductReply_Image{}
	mi := &file_v1_catalog_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductReply_Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductReply_Image) ProtoMessage() {}

func (x *GetProductReply_Image) ProtoReflect() protoreflect.Message {
	mi := &file_v1_catalog_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductReply_Image.ProtoReflect.Descriptor instead.
func (*GetProductReply_Image) Descriptor() ([]byte, []int) {
	return file_v1_catalog_proto_rawDescGZIP(), []int{7, 0}
}

func (x *GetProductReply_Image) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type UpdateProductReq_Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductReq_Image) Reset() {
	*x = UpdateProductReq_Image{}
	mi := &file_v1_catalog_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductReq_Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductReq_Image) ProtoMessage() {}

func (x *UpdateProductReq_Image) ProtoReflect() protoreflect.Message {
	mi := &file_v1_catalog_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductReq_Image.ProtoReflect.Descriptor instead.
func (*UpdateProductReq_Image) Descriptor() ([]byte, []int) {
	return file_v1_catalog_proto_rawDescGZIP(), []int{8, 0}
}

func (x *UpdateProductReq_Image) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type UpdateProductReply_Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductReply_Image) Reset() {
	*x = UpdateProductReply_Image{}
	mi := &file_v1_catalog_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductReply_Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductReply_Image) ProtoMessage() {}

func (x *UpdateProductReply_Image) ProtoReflect() protoreflect.Message {
	mi := &file_v1_catalog_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductReply_Image.ProtoReflect.Descriptor instead.
func (*UpdateProductReply_Image) Descriptor() ([]byte, []int) {
	return file_v1_catalog_proto_rawDescGZIP(), []int{9, 0}
}

func (x *UpdateProductReply_Image) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_v1_catalog_proto protoreflect.FileDescriptor

const file_v1_catalog_proto_rawDesc = "" +
	"\n" +
	"\x10v1/catalog.proto\x12\x12catalog.service.v1\x1a\x1cgoogle/api/annotations.proto\"H\n" +
	"\x0eListProductReq\x12\x19\n" +
	"\bpage_num\x18\x01 \x01(\x03R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\"U\n" +
	"\x17listProductNextTokenReq\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"\xa7\x02\n" +
	"\x10ListProductReply\x12F\n" +
	"\aresults\x18\x01 \x03(\v2,.catalog.service.v1.ListProductReply.ProductR\aresults\x1a\xca\x01\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x03R\x05count\x12H\n" +
	"\x05image\x18\x05 \x03(\v22.catalog.service.v1.ListProductReply.Product.ImageR\x05image\x1a\x19\n" +
	"\x05Image\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\xea\x02\n" +
	"\x19ListProductReplyNextToken\x12O\n" +
	"\aresults\x18\x01 \x03(\v25.catalog.service.v1.ListProductReplyNextToken.ProductR\aresults\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x1a\xd3\x01\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x03R\x05count\x12Q\n" +
	"\x05image\x18\x05 \x03(\v2;.catalog.service.v1.ListProductReplyNextToken.Product.ImageR\x05image\x1a\x19\n" +
	"\x05Image\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\xbb\x01\n" +
	"\x10CreateProductReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\x12@\n" +
	"\x05image\x18\x04 \x03(\v2*.catalog.service.v1.CreateProductReq.ImageR\x05image\x1a\x19\n" +
	"\x05Image\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\xcf\x01\n" +
	"\x12CreateProductReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x03R\x05count\x12B\n" +
	"\x05image\x18\x05 \x03(\v2,.catalog.service.v1.CreateProductReply.ImageR\x05image\x1a\x19\n" +
	"\x05Image\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x1f\n" +
	"\rGetProductReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xc9\x01\n" +
	"\x0fGetProductReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x03R\x05count\x12?\n" +
	"\x05image\x18\x05 \x03(\v2).catalog.service.v1.GetProductReply.ImageR\x05image\x1a\x19\n" +
	"\x05Image\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\xcb\x01\n" +
	"\x10UpdateProductReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x03R\x05count\x12@\n" +
	"\x05image\x18\x05 \x03(\v2*.catalog.service.v1.UpdateProductReq.ImageR\x05image\x1a\x19\n" +
	"\x05Image\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\xcf\x01\n" +
	"\x12UpdateProductReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x03R\x05count\x12B\n" +
	"\x05image\x18\x05 \x03(\v2,.catalog.service.v1.UpdateProductReply.ImageR\x05image\x1a\x19\n" +
	"\x05Image\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\"\n" +
	"\x10DeleteProductReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x14\n" +
	"\x12DeleteProductReply2\xd5\x04\n" +
	"\aCatalog\x12Y\n" +
	"\vListProduct\x12\".catalog.service.v1.ListProductReq\x1a$.catalog.service.v1.ListProductReply\"\x00\x12t\n" +
	"\x14ListProductNextToken\x12+.catalog.service.v1.listProductNextTokenReq\x1a-.catalog.service.v1.ListProductReplyNextToken\"\x00\x12_\n" +
	"\rCreateProduct\x12$.catalog.service.v1.CreateProductReq\x1a&.catalog.service.v1.CreateProductReply\"\x00\x12V\n" +
	"\n" +
	"GetProduct\x12!.catalog.service.v1.GetProductReq\x1a#.catalog.service.v1.GetProductReply\"\x00\x12_\n" +
	"\rUpdateProduct\x12$.catalog.service.v1.UpdateProductReq\x1a&.catalog.service.v1.UpdateProductReply\"\x00\x12_\n" +
	"\rDeleteProduct\x12$.catalog.service.v1.DeleteProductReq\x1a&.catalog.service.v1.DeleteProductReply\"\x00B\x1bZ\x19api/catalog/service/v1;v1b\x06proto3"

var (
	file_v1_catalog_proto_rawDescOnce sync.Once
	file_v1_catalog_proto_rawDescData []byte
)

func file_v1_catalog_proto_rawDescGZIP() []byte {
	file_v1_catalog_proto_rawDescOnce.Do(func() {
		file_v1_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_catalog_proto_rawDesc), len(file_v1_catalog_proto_rawDesc)))
	})
	return file_v1_catalog_proto_rawDescData
}

var file_v1_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_v1_catalog_proto_goTypes = []any{
	(*ListProductReq)(nil),                          // 0: catalog.service.v1.ListProductReq
	(*ListProductNextTokenReq)(nil),                 // 1: catalog.service.v1.listProductNextTokenReq
	(*ListProductReply)(nil),                        // 2: catalog.service.v1.ListProductReply
	(*ListProductReplyNextToken)(nil),               // 3: catalog.service.v1.ListProductReplyNextToken
	(*CreateProductReq)(nil),                        // 4: catalog.service.v1.CreateProductReq
	(*CreateProductReply)(nil),                      // 5: catalog.service.v1.CreateProductReply
	(*GetProductReq)(nil),                           // 6: catalog.service.v1.GetProductReq
	(*GetProductReply)(nil),                         // 7: catalog.service.v1.GetProductReply
	(*UpdateProductReq)(nil),                        // 8: catalog.service.v1.UpdateProductReq
	(*UpdateProductReply)(nil),                      // 9: catalog.service.v1.UpdateProductReply
	(*DeleteProductReq)(nil),                        // 10: catalog.service.v1.DeleteProductReq
	(*DeleteProductReply)(nil),                      // 11: catalog.service.v1.DeleteProductReply
	(*ListProductReply_Product)(nil),                // 12: catalog.service.v1.ListProductReply.Product
	(*ListProductReply_Product_Image)(nil),          // 13: catalog.service.v1.ListProductReply.Product.Image
	(*ListProductReplyNextToken_Product)(nil),       // 14: catalog.service.v1.ListProductReplyNextToken.Product
	(*ListProductReplyNextToken_Product_Image)(nil), // 15: catalog.service.v1.ListProductReplyNextToken.Product.Image
	(*CreateProductReq_Image)(nil),                  // 16: catalog.service.v1.CreateProductReq.Image
	(*CreateProductReply_Image)(nil),                // 17: catalog.service.v1.CreateProductReply.Image
	(*GetProductReply_Image)(nil),                   // 18: catalog.service.v1.GetProductReply.Image
	(*UpdateProductReq_Image)(nil),                  // 19: catalog.service.v1.UpdateProductReq.Image
	(*UpdateProductReply_Image)(nil),                // 20: catalog.service.v1.UpdateProductReply.Image
}
var file_v1_catalog_proto_depIdxs = []int32{
	12, // 0: catalog.service.v1.ListProductReply.results:type_name -> catalog.service.v1.ListProductReply.Product
	14, // 1: catalog.service.v1.ListProductReplyNextToken.results:type_name -> catalog.service.v1.ListProductReplyNextToken.Product
	16, // 2: catalog.service.v1.CreateProductReq.image:type_name -> catalog.service.v1.CreateProductReq.Image
	17, // 3: catalog.service.v1.CreateProductReply.image:type_name -> catalog.service.v1.CreateProductReply.Image
	18, // 4: catalog.service.v1.GetProductReply.image:type_name -> catalog.service.v1.GetProductReply.Image
	19, // 5: catalog.service.v1.UpdateProductReq.image:type_name -> catalog.service.v1.UpdateProductReq.Image
	20, // 6: catalog.service.v1.UpdateProductReply.image:type_name -> catalog.service.v1.UpdateProductReply.Image
	13, // 7: catalog.service.v1.ListProductReply.Product.image:type_name -> catalog.service.v1.ListProductReply.Product.Image
	15, // 8: catalog.service.v1.ListProductReplyNextToken.Product.image:type_name -> catalog.service.v1.ListProductReplyNextToken.Product.Image
	0,  // 9: catalog.service.v1.Catalog.ListProduct:input_type -> catalog.service.v1.ListProductReq
	1,  // 10: catalog.service.v1.Catalog.ListProductNextToken:input_type -> catalog.service.v1.listProductNextTokenReq
	4,  // 11: catalog.service.v1.Catalog.CreateProduct:input_type -> catalog.service.v1.CreateProductReq
	6,  // 12: catalog.service.v1.Catalog.GetProduct:input_type -> catalog.service.v1.GetProductReq
	8,  // 13: catalog.service.v1.Catalog.UpdateProduct:input_type -> catalog.service.v1.UpdateProductReq
	10, // 14: catalog.service.v1.Catalog.DeleteProduct:input_type -> catalog.service.v1.DeleteProductReq
	2,  // 15: catalog.service.v1.Catalog.ListProduct:output_type -> catalog.service.v1.ListProductReply
	3,  // 16: catalog.service.v1.Catalog.ListProductNextToken:output_type -> catalog.service.v1.ListProductReplyNextToken
	5,  // 17: catalog.service.v1.Catalog.CreateProduct:output_type -> catalog.service.v1.CreateProductReply
	7,  // 18: catalog.service.v1.Catalog.GetProduct:output_type -> catalog.service.v1.GetProductReply
	9,  // 19: catalog.service.v1.Catalog.UpdateProduct:output_type -> catalog.service.v1.UpdateProductReply
	11, // 20: catalog.service.v1.Catalog.DeleteProduct:output_type -> catalog.service.v1.DeleteProductReply
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_v1_catalog_proto_init() }
func file_v1_catalog_proto_init() {
	if File_v1_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_catalog_proto_rawDesc), len(file_v1_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_catalog_proto_goTypes,
		DependencyIndexes: file_v1_catalog_proto_depIdxs,
		MessageInfos:      file_v1_catalog_proto_msgTypes,
	}.Build()
	File_v1_catalog_proto = out.File
	file_v1_catalog_proto_goTypes = nil
	file_v1_catalog_proto_depIdxs = nil
}
