services:
  user-db:
    image: mysql:8
    hostname: user-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: dangerous
      MYSQL_DATABASE: test
  catalog-db:
    image: mysql:8
    hostname: catalog-db
    environment:
      MYSQL_ROOT_PASSWORD: dangerous
  cart-db:
    image: mongo:4
    hostname: cart-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dangerous
  order-db:
    image: mysql:8
    hostname: order-db
    environment:
      MYSQL_ROOT_PASSWORD: dangerous
  user-redis:
    image: redis:7
    hostname: user-redis
    ports:
      - "6379:6379"
  catalog-redis:
    image: redis:7
    hostname: catalog-redis
    ports:
      - "6380:6379"
  cart-redis:
    image: redis:7
    hostname: cart-redis
    ports:
      - "6381:6379"
  order-redis:
    image: redis:7
    hostname: order-redis
    ports:
      - "6382:6379"
  payment-redis:
    image: redis:7
    hostname: payment-redis
    ports:
      - "6383:6379"
  jaeger:
    image: jaegertracing/all-in-one:latest
    hostname: jaeger
    ports:
      - "16686:16686" 
      - "14268:14268" 
    environment:
      - COLLECTOR_OTLP_ENABLED=true
  consul:
    image: consul:1.15
    hostname: consul
    ports:
      - "8500:8500"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    command: agent -server -bootstrap -ui -client=0.0.0.0
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:2
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
